# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  macos:
    runs-on: macos-12
    env:
      PACKAGENAME: bika_py37_macos
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==4.6
        pip install https://github.com/tonquer/waifu2x-vulkan/releases/download/v1.1.6/sr_ncnn_vulkan-1.2.0-cp39-cp39-macosx_10_9_universal2.whl
        pip install -r src/requirements_macos.txt
        brew install create-dmg
    - name: Build
      run: |
        cd src
        cp ../res/icon/Icon.icns ./
        pyinstaller --clean --onedir --name PicACG \
            --hidden-import waifu2x_vulkan --hidden-import PySide6 --hidden-import requests \
            --hidden-import urllib3 --hidden-import websocket-client --hidden-import pillow \
            --hidden-import config \
            --hidden-import component \
            --hidden-import server \
            --hidden-import task \
            --hidden-import tools \
            --hidden-import view \
            --strip --windowed -i Icon.icns \
            start.py
        # rm -rf dist/PicACG
        # cp Icon.icns dist/
        # ln -s /Applications/   dist/Applications
        cp -avf db dist/PicACG.app/Contents/MacOS
        xattr -cr dist/PicACG.app
        create-dmg --volname "PicACG" --volicon "Icon.icns" --icon "PicACG.app" 200 190 \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --hide-extension "PicACG.app" --app-drop-link 600 185 \
            ${{ env.PACKAGENAME }}.dmg dist/PicACG.app

        zip -9 bika.zip ${{ env.PACKAGENAME }}.dmg
        mv ${{ env.PACKAGENAME }}.dmg ..
        mv bika.zip ..
        cd ..
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: bika.zip
        retention-days: 7
        
  windows:
    runs-on: windows-latest
    env:
      PACKAGENAME: bika_py37_windows_x64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==4.8
        pip install -r src\requirements.txt
    - name: Build
      run: |
        cd src
        cp ..\res\icon\icon.ico .\

        pyinstaller -F -w -i icon.ico start.py
        mv dist bika
        Copy-Item -Verbose -Recurse -Path db -Destination bika/
        cp ..\LICENSE bika\
        cp ..\CHANGELOG bika\
        cd ..
        mkdir ${{ env.PACKAGENAME }}
        mv src\bika ${{ env.PACKAGENAME }}
        7z a -r "$($Env:PACKAGENAME + '.zip')" "bika"
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}
        retention-days: 7
        
  windows7:
    runs-on: windows-latest
    env:
      PACKAGENAME: bika_py37_windows7_x64
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==4.6
        pip install -r src\requirements_win7.txt
    - name: Build
      run: |
        cd src
        cp ..\res\icon\icon.ico .\
        pyinstaller -F -w -i icon.ico start.py
        mv dist bika
        Copy-Item -Verbose -Recurse -Path db -Destination bika/
        cp ..\LICENSE bika\
        cp ..\CHANGELOG bika\
        cd ..
        mkdir ${{ env.PACKAGENAME }}
        mv src\bika ${{ env.PACKAGENAME }}
        7z a -r "$($Env:PACKAGENAME + '.zip')" "bika"
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}
        retention-days: 7

  ubuntu:
    runs-on: ubuntu-latest
    env:
      PACKAGENAME: bika_py37_linux
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install -y fuse libfuse2
        python -m pip install --upgrade pip
        pip install pyinstaller==4.8
        pip install https://github.com/tonquer/waifu2x-vulkan/releases/download/v1.1.6/sr_ncnn_vulkan-1.2.0-cp37-cp37m-linux_x86_64.whl
        pip install -r src/requirements.txt
    - name: Build
      run: |
        cd src
        pyinstaller -w start.py
        cd dist
        mkdir -p picacg.AppRun/usr/bin
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        cp -r ../../res/appimage/* picacg.AppRun/
        cp -r ../../res/icon/logo_round.png picacg.AppRun/PicACG.png
        cp -r start/* picacg.AppRun/usr/bin/
        cp -r ../db  picacg.AppRun/

        mv picacg.AppRun/usr/bin/start picacg.AppRun/usr/bin/PicACG
        chmod +x picacg.AppRun/AppRun
        chmod +x picacg.AppRun/usr/bin/PicACG
        ./appimagetool-x86_64.AppImage picacg.AppRun
        mv PicACG-x86_64.AppImage ../../${{ env.PACKAGENAME }}-x86_64.AppImage
        cd ../..
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}-x86_64.AppImage
        retention-days: 7